version: '3.8'

services:
  foody.swagger:
      image: ${DOCKER_REGISTRY-}foodyswagger
      container_name: foody.swagger
      build:
        context: .
        dockerfile: Foody.Web.Swagger/Dockerfile
      ports:
        - "8080:8080"
        - "8081:8081"
  postgres:
    image: postgres:15
    container_name: foody-postgres-db
    environment:
      POSTGRES_DB: foody
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: 
